name: Lets See

on:
  pull_request:
    branches: [ staging ]

jobs:
  configuring-changes:
    name: Checking Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
       

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Analyze code
        run: flutter analyze